baseURL = 'https://omerfarukdemirel.com.tr'
languageCode = 'tr-TR'
title = 'OmerF'
theme = 'PaperMod'
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License. @omerfdmrl'
enableRobotsTXT = true
enableRssXML = true
defaultContentLanguage = 'tr'
defaultTheme = 'dark'
disableThemeToggle = true

[taxonomies]
category = 'categories'
tag = 'tags'

[menu]
[[menu.main]]
  name = 'Makaleler'
  url = '/posts/'
  weight = -110
[[menu.main]]
  name = 'Etiketler'
  url = '/tags/'
  weight = -100
[[menu.main]]
  name = 'Ara'
  url = '/search/'
  weight = -90

[params]
  ShowShareButtons = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  comments = true
[params.homeInfoParams]
  Title = 'Ömer Faruk Demirel'
  Content = 'Bloguma hoşgeldiniz'
[params.cover]
  responsiveImages = true
  linkFullImages = true
[params.editPost]
  URL = "https://github.com/omerfdmrl/omerfarukdemirel.com.tr/tree/main/content/"
  Text = "Yazıyı Düzenle"
  appendFilePath = true
[params.assets]
  disableFingerprinting = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[permalinks]
  posts = '/post/:slugorfilename/'
  pages = '/page/:slugorfilename/'
